import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import { ApolloWrapper } from "./ApolloWrapper";
import Header from "./components/Header";

const pretendard = localFont({src : './fonts/PretendardVariable.woff2',
                              variable : '--font-prentendard',
                              display : 'swap'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport : 'width=device-width, initial-scale=1'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={pretendard.className}>
      <body>
        <Header/>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
