import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import { ApolloWrapper } from "./ApolloWrapper";
import Header from "./components/Header";
import OAuthProvider from "./OAuthProvider";

const pretendard = localFont({src : './fonts/PretendardVariable.woff2',
                              variable : '--font-prentendard',
                              display : 'swap'});


export const metadata: Metadata = {
  title: "호텔스닷컴 - 해외 국내 여행에 필요한 호텔, 숙박 예약 사이트 | Hotels.com",
  description: "Generated by create next app",
  viewport : 'width=device-width, initial-scale=1'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={pretendard.className}>
      <body>
        <OAuthProvider>
          <Header/>
          <ApolloWrapper>{children}</ApolloWrapper>
        </OAuthProvider>
      </body>
    </html>
  );
}
